import "./globals.css";
import Header from "@/Components/Header";

export const metadata = {
  title: "Love UI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className='flex flex-col items-center h-screen'>
        {/* {Header} aise nhi */}
        {/* aise */}
        <div className="w-full mb-5 py-5 bg-pink-500 flex items-center"><Header/></div> {/* import components as tag */}
        {children}
      </body>
    </html>
  );
}
